name: mukhla_splitw
description: MUKHLA - Kharche Pai Charcha - Premium Expense Tracker

publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  google_sign_in: ^6.2.1
  firebase_messaging: ^15.1.0
  firebase_storage: ^12.1.3

  # State Management
  provider: ^6.1.1

  # UI Components
  cupertino_icons: ^1.0.6

  # Utils
  intl: ^0.19.0
  uuid: ^4.3.3

  # Share & Utils
  share_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true